### ISSUE TITLE
OpenAPI 3 Schema issues

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/agent-specs#13]
- email `type` is not defined
- In schemas.Agent.properties.data.type : `type ` should not be string but the 'agent' constant as defined per JSON API
- query.sort description should be improved

**Comment by xuemeigan** [comment]
1. Added email type and improved sort order string : https://github.com/xuemeigan/agent-specs/commit/4ed77acdd6b47a9ec38d595ac5f52646d89f2198
2. I think Open API does not provide constant type : https://swagger.io/docs/specification/data-models/data-types/

**Comment by cgendreau** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/1620
It should be possible to use 'const' in Open API 3.1: see https://github.com/OAI/OpenAPI-Specification/issues/1313

**Comment by xuemeigan** [comment]
Used enum of 1 for agent type:  https://github.com/xuemeigan/agent-specs/commit/05541f919d5c42aa3a04c8e4579e0cd11ebbf6ed

**Comment by cgendreau** [comment]
Please send a new PR, the previous one is already merged.

**Comment by cgendreau** [comment]
Fixed by https://github.com/DINA-Web/agent-specs/pull/15
