### ISSUE TITLE
Person type should be constant

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/agent-specs#24]
Person type should be constant 'person' as defined by JSON-API.
https://github.com/DINA-Web/agent-specs/blob/master/schema/agent.yml#L174

**Comment by xuemeigan** [comment]
We are currently using enum of 1 since const type is  in the future PR : https://github.com/DINA-Web/agent-specs/issues/13.

**Comment by cgendreau** [comment]
Not currently, `enum` is not in the current file.

**Comment by xuemeigan** [comment]
No,  I will send the PR to change to use enum for person type
