### ISSUE TITLE
Add organization to schema

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/agent-specs#26]
As per https://github.com/DINA-Web/dina-model-concepts/issues/40

endpoint is `organization` and there is only 2 fields: `name `and `aliases`.

**Comment by cgendreau** [comment]
Should be referenced in agent.yml

**Comment by xuemeigan** [comment]
Currently agent.yml is actually describing person , to confirm,  we would like to
1. Rename agent.yml to person.yml
2. Write agent.yml, similar to https://github.com/DINA-Web/object-store-specs/blob/master/schema/object-store-api.yaml,
to incorporate person and organization.

**Comment by cgendreau** [comment]
yes, exactly

**Comment by xuemeigan** [comment]
Ready for review
