### ISSUE TITLE
Add person organization relationship

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/agent-specs#28]
The relationship is missing from the schema

**Comment by cgendreau** [comment]
Organization should be a real relationship:

```
"relationships": {
      "organizations": {
        "data": { "type": "organization", "id": "xyz" }
      }
```

https://jsonapi.org/format/#document-compound-documents

**Comment by xuemeigan** [comment]
Made the relationship compliant with the json api spec:https://jsonapi.org/format/#document-compound-documents in below commit: 
https://github.com/DINA-Web/agent-specs/pull/29/commits/e092dcc7342de24d23b2398895e8d789d825863d

**Comment by xuemeigan** [comment]
- Fix null relationships in generated doc
https://github.com/DINA-Web/agent-specs/pull/29/commits/a18eb2061660c17aec5055331e075bd3ed364b24
