### ISSUE TITLE
createdOn and createdBy missing in schema

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/agent-specs#34]
`createdOn` and `createdBy` are missing from person and organization schema. `createdOn` should be specified as a date-time format and they are both mandatory on the response only (you can't send it in a data mutation).

**Comment by xuemeigan** [comment]
Need to do investigation,  see if there is a way to conditional the current common component to add or remove the createdOn

**Comment by cgendreau** [comment]
it's the same thing as the `id`, it is read only.

**Comment by cgendreau** [comment]
see `readonly` http://spec.openapis.org/oas/v3.0.3

**Comment by cgendreau** [comment]
`createdBy` should also be `readOnly`, it is set server-side. `date-time` should be more specific about the format and force 
ISO 8601.

**Comment by xuemeigan** [comment]
- Update createdBy to readOnly
- Update createdOn description and add ISO-8601 date-format examples
https://github.com/DINA-Web/agent-specs/commit/4fb20cf3245b157269fdf5647fd6db8fec38bffe

**Comment by cgendreau** [comment]
`createdOn` can only be returned in 1 format. The specs should only specify 1 format.

**Comment by xuemeigan** [comment]
So should we use the UTC time: 1985-04-12T23:20:50.52Z, as createdOn is server side generated

**Comment by xuemeigan** [comment]
- Update createOn to use one example
https://github.com/DINA-Web/agent-specs/pull/35/commits/f58bdbacab4e8c73635aba38b6fb0ad9dce85dc1
